nodeLinker: node-modules

# Allow workspace dependencies to change without breaking immutable installs
checksumBehavior: update

enableGlobalCache: true

npmScopes:
    sofie-automation:
        npmRegistryServer: 'https://npm.pkg.github.com'
        npmAlwaysAuth: true
        npmAuthToken: '${NODE_AUTH_TOKEN:-}'

npmRegistries:
    'https://npm.pkg.github.com':
        npmAlwaysAuth: true
        npmAuthToken: '${NODE_AUTH_TOKEN:-}'

# querystring is replaced with URLSearchParams via patches on node-vmix and vmix-js-utils
npmAuditExcludePackages:
    - querystring
