name: 'Validate dependencies'
description: 'Validate dependencies'
runs:
    using: 'composite'
    steps:
        - name: Install dependencies
          uses: ./.github/actions/yarn-install
          with:
              clean-cache: 'true'

        - name: Check dependencies
          shell: bash
          run: yarn npm audit --all --recursive --environment production --severity moderate
