name: Build

on:
    workflow_call:
        inputs:
            fetch-depth:
                description: 'Checkout fetch depth'
                required: false
                type: string
                default: '0'
            node-version:
                description: 'Node.js version'
                required: false
                type: string
                default: '24'
            yarn-version:
                description: 'Yarn version'
                required: false
                type: string
                default: '4.1.0'

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Access repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}
                  fetch-depth: ${{ inputs.fetch-depth }}

            - name: Setup Node.js and Yarn
              uses: ./.github/actions/setup-node-yarn
              with:
                  node-version: ${{ inputs.node-version }}
                  yarn-version: ${{ inputs.yarn-version }}

            - name: Install dependencies
              uses: ./.github/actions/yarn-install

            - name: Build
              run: yarn build

            - name: Upload client build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ github.event.repository.name }}-client
                  path: client/dist

            - name: Upload server build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ github.event.repository.name }}-server
                  path: server/dist
