name: CI

permissions:
    contents: read

on:
    push:
    pull_request:

jobs:
    cache-dependencies:
        uses: ./.github/workflows/util-cache-dependencies.yml

    prebuild:
        needs: cache-dependencies
        uses: ./.github/workflows/util-prebuild.yml

    test:
        needs: cache-dependencies
        uses: ./.github/workflows/util-test.yml

    validate-dependencies:
        uses: ./.github/workflows/util-validate-dependencies.yml
